export default [
    {id: 1, url:"src/assets/Images/news/news-2.jpg", date:"Jun 25, 2025", author:"Akari Mizunashi", title:"Unlocking the Power of AI Healthcare"},
    {id: 2, url:"src/assets/Images/news/news-2.jpg", date:"Jun 25, 2025", author:"Akari Mizunashi", title:"The Future of Health: AI-Driven Patient Care"},
    {id: 3, url:"src/assets/Images/news/news-3.jpg", date:"Jun 25, 2025", author:"Akari Mizunashi", title:"Navigating Healthcare: Your Guide to Asklepios"},
    {id: 5, url:"src/assets/Images/news/news-5.jpg", date:"Jun 25, 2025", author:"Akari Mizunashi", title:"Unlocking the Power of AI Healthcare"},
    {id: 4, url:"src/assets/Images/news/news-4.jpg", date:"Jun 25, 2025", author:"Akari Mizunashi", title:"The Role of AI in Revolutionizing Healthcare"},
    {id: 6, url:"src/assets/Images/news/news-6.jpg", date:"Jun 25, 2025", author:"Akari Mizunashi", title:"The Future of Health: AI-Driven Patient Care"},
    {id: 7, url:"src/assets/Images/news/news-7.jpg", date:"Jun 25, 2025", author:"Akari Mizunashi", title:"Unlocking the Power of AI Healthcare"},
    {id: 8, url:"src/assets/Images/news/news-8.jpg", date:"Jun 25, 2025", author:"Akari Mizunashi", title:"The Future of Health: AI-Driven Patient Care"},
    {id: 9, url:"src/assets/Images/news/news-9.jpg", date:"Jun 25, 2025", author:"Akari Mizunashi", title:"Navigating Healthcare: Your Guide to Asklepios"},
    {id: 10, url:"src/assets/Images/news/news-10.jpg", date:"Jun 25, 2025", author:"Akari Mizunashi", title:"The Role of AI in Revolutionizing Healthcare"},
    {id: 11, url:"src/assets/Images/news/news-6.jpg", date:"Jun 25, 2025", author:"Akari Mizunashi", title:"The Future of Health: AI-Driven Patient Care"},
    {id: 12, url:"src/assets/Images/news/news-7.jpg", date:"Jun 25, 2025", author:"Akari Mizunashi", title:"Unlocking the Power of AI Healthcare"},
    {id: 13, url:"src/assets/Images/news/news-2.jpg", date:"Jun 25, 2025", author:"Akari Mizunashi", title:"The Future of Health: AI-Driven Patient Care"},
    {id: 14, url:"src/assets/Images/news/news-8.jpg", date:"Jun 25, 2025", author:"Akari Mizunashi", title:"The Future of Health: AI-Driven Patient Care"},
    {id: 15, url:"src/assets/Images/news/news-9.jpg", date:"Jun 25, 2025", author:"Akari Mizunashi", title:"Navigating Healthcare: Your Guide to Asklepios"},
    {id: 16, url:"src/assets/Images/news/news-3.jpg", date:"Jun 25, 2025", author:"Akari Mizunashi", title:"Navigating Healthcare: Your Guide to Asklepios"},
    {id: 17, url:"src/assets/Images/news/news-4.jpg", date:"Jun 25, 2025", author:"Akari Mizunashi", title:"The Role of AI in Revolutionizing Healthcare"},
    {id: 18, url:"src/assets/Images/news/news-1.jpg", date:"Jun 25, 2025", author:"Akari Mizunashi", title:"Unlocking the Power of AI Healthcare"},
]